/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.parks;

import br.com.parks.entity.OLT;
import br.com.parks.entity.ONU;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tiago
 */
public class BWProfilePanel extends javax.swing.JPanel {

    private final JTabbedPane panel;
    private OLT olt;
    private ONU onu;

    public BWProfilePanel(JTabbedPane panel) {
        this.panel = panel;
        initComponents();
    }

    public BWProfilePanel(JTabbedPane panel, OLT olt) {
        this.panel = panel;
        this.olt = olt;
        initComponents();
        displayBwProfileTable(olt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbBwp = new javax.swing.JTable();
        txtBwName = new javax.swing.JTextField();
        lbBwName = new javax.swing.JLabel();
        btAddBwp = new javax.swing.JButton();
        lbBwpAssured = new javax.swing.JLabel();
        txtBwpAssured = new javax.swing.JTextField();
        lbBwpMaximum = new javax.swing.JLabel();
        txtBwpMaximum = new javax.swing.JTextField();
        btClose1 = new javax.swing.JButton();

        tbBwp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Type", "Fixed", "Assured", "Maximum"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbBwp);
        if (tbBwp.getColumnModel().getColumnCount() > 0) {
            tbBwp.getColumnModel().getColumn(0).setHeaderValue("Name");
            tbBwp.getColumnModel().getColumn(1).setHeaderValue("Type");
            tbBwp.getColumnModel().getColumn(2).setHeaderValue("Fixed");
            tbBwp.getColumnModel().getColumn(3).setHeaderValue("Assured");
            tbBwp.getColumnModel().getColumn(4).setHeaderValue("Maximum");
        }

        lbBwName.setText("Name:");

        btAddBwp.setText("Add BW Profile");

        lbBwpAssured.setText("Assured:");

        lbBwpMaximum.setText("Maximum:");

        btClose1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DeleteRed2.png"))); // NOI18N
        btClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClose1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lbBwName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBwName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbBwpAssured)
                                    .addComponent(lbBwpMaximum))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBwpAssured)
                                    .addComponent(txtBwpMaximum, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAddBwp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btClose1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBwName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbBwName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBwpAssured, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbBwpAssured))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBwpMaximum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbBwpMaximum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(btAddBwp))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btClose1)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClose1ActionPerformed
        panel.remove(panel.indexOfComponent(this));
    }//GEN-LAST:event_btClose1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddBwp;
    private javax.swing.JButton btClose1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBwName;
    private javax.swing.JLabel lbBwpAssured;
    private javax.swing.JLabel lbBwpMaximum;
    private javax.swing.JTable tbBwp;
    private javax.swing.JTextField txtBwName;
    private javax.swing.JTextField txtBwpAssured;
    private javax.swing.JTextField txtBwpMaximum;
    // End of variables declaration//GEN-END:variables

    private void displayBwProfileTable(OLT olt) {
        DefaultTableModel dtm = (DefaultTableModel) tbBwp.getModel();
        for (String r : olt.getBwProfile()) {
            String[] rbwp=r.split(",");
            dtm.addRow(new String[]{rbwp[0], rbwp[1], rbwp[2], rbwp[3],rbwp[4] });
        }
        tbBwp.setModel(dtm);
    }

}
