/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.parks;

import br.com.parks.entity.OLT;
import br.com.parks.entity.ONU;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tiago
 */
public class VlanTranslateProfilePanel extends javax.swing.JPanel {

    private final JTabbedPane panel;
    private OLT olt;
    private ONU onu;
    
    public VlanTranslateProfilePanel(JTabbedPane panel) {
        this.panel=panel;
        initComponents();
    }

    public VlanTranslateProfilePanel(JTabbedPane panel, OLT olt) {
        this.panel = panel;
        this.olt = olt;
        initComponents();
        displayVtpNameTable();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spVtpName = new javax.swing.JScrollPane();
        tbVtpName = new javax.swing.JTable();
        txtVtpName = new javax.swing.JTextField();
        btAddVtpName = new javax.swing.JButton();
        spVtpItem = new javax.swing.JScrollPane();
        tbVtpItem = new javax.swing.JTable();
        lbType = new javax.swing.JLabel();
        cbType = new javax.swing.JComboBox();
        lbVlan = new javax.swing.JLabel();
        cbVlan = new javax.swing.JComboBox();
        btAddVtp = new javax.swing.JButton();
        btClose1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        tbVtpName.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbVtpName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbVtpNameMouseClicked(evt);
            }
        });
        spVtpName.setViewportView(tbVtpName);
        if (tbVtpName.getColumnModel().getColumnCount() > 0) {
            tbVtpName.getColumnModel().getColumn(0).setMinWidth(40);
            tbVtpName.getColumnModel().getColumn(0).setMaxWidth(40);
            tbVtpName.getColumnModel().getColumn(1).setResizable(false);
        }

        btAddVtpName.setText("Add");

        tbVtpItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDX", "Mode", "Operation", "VLAN X", "VLAN C", "Filter Prio", "Vlan Prio", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spVtpItem.setViewportView(tbVtpItem);
        if (tbVtpItem.getColumnModel().getColumnCount() > 0) {
            tbVtpItem.getColumnModel().getColumn(0).setMinWidth(35);
            tbVtpItem.getColumnModel().getColumn(0).setMaxWidth(35);
        }

        lbType.setText("Type:");

        lbVlan.setText("Vlan:");

        btAddVtp.setForeground(new java.awt.Color(3, 122, 18));
        btAddVtp.setText("Add Trans. Profile");

        btClose1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DeleteRed2.png"))); // NOI18N
        btClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClose1ActionPerformed(evt);
            }
        });

        jButton1.setForeground(new java.awt.Color(236, 7, 7));
        jButton1.setText("Remove VTP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lbType)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbVlan)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbVlan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(spVtpItem, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAddVtp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtVtpName, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btAddVtpName))
                        .addComponent(spVtpName, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(btClose1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVtpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAddVtpName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spVtpName, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(spVtpItem, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbType)
                    .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbVlan)
                    .addComponent(cbVlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btAddVtp)
                        .addComponent(jButton1))
                    .addComponent(btClose1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClose1ActionPerformed
        panel.remove(panel.indexOfComponent(this));
    }//GEN-LAST:event_btClose1ActionPerformed

    private void tbVtpNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbVtpNameMouseClicked
       if (olt != null) {
            cleanVtpItemTable();
            int row = tbVtpName.getSelectedRow();
            List<String> vtpi = new ArrayList<String>();
            String f = tbVtpName.getModel().getValueAt(row, 1).toString();
            for (String v : olt.getVlanTranslate()) {
                if (v.contains(f)) {
                    vtpi.add(v);
                }
            }
            displayVtpItemTable(vtpi);
        }
    }//GEN-LAST:event_tbVtpNameMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddVtp;
    private javax.swing.JButton btAddVtpName;
    private javax.swing.JButton btClose1;
    private javax.swing.JComboBox cbType;
    private javax.swing.JComboBox cbVlan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbType;
    private javax.swing.JLabel lbVlan;
    private javax.swing.JScrollPane spVtpItem;
    private javax.swing.JScrollPane spVtpName;
    private javax.swing.JTable tbVtpItem;
    private javax.swing.JTable tbVtpName;
    private javax.swing.JTextField txtVtpName;
    // End of variables declaration//GEN-END:variables
    
    private void displayVtpNameTable(){
        DefaultTableModel dtm = (DefaultTableModel) tbVtpName.getModel();
        int count = 0;
        cleanVtpNameTable();
        String fname = "";
        for (String r : olt.getVlanTranslate()) {
            String[] rvtpi = r.split(",");
            if (!rvtpi[0].equals(fname)) {
                count++;
                dtm.addRow(new String[]{Integer.toString(count), rvtpi[0]});
            }
            fname = rvtpi[0];
        }
        tbVtpName.setModel(dtm);
    }
    
    private void displayVtpItemTable(List<String> vtp){
        DefaultTableModel dtm = (DefaultTableModel) tbVtpItem.getModel();
        for (String r : vtp) {
            String[] rfp = r.split(",");
            dtm.addRow(new String[]{rfp[1], rfp[2], rfp[3], rfp[4], rfp[5], rfp[6], rfp[7], rfp.length==9 ? rfp[8] : ""});
        }
        tbVtpItem.setModel(dtm);
    }
    
    public void cleanVtpNameTable(){
        DefaultTableModel dtm = (DefaultTableModel) tbVtpName.getModel();
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
    }

    public void cleanVtpItemTable(){
        DefaultTableModel dtm = (DefaultTableModel) tbVtpItem.getModel();
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
    }
}
